#
# EcoItems
# by Auxilor
#

discover-recipes: true
cannot-afford:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
raytrace-distance: 80
check-offhand: false
cannot-afford-type:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
potions:
  icon:
    triggered: true
    permanent: true
  ambient:
    triggered: true
    permanent: false
  particles:
    triggered: true
    permanent: false
cooldown:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
point-names:
  example_point: Nicely Formatted Point
use-faster-move-trigger: true

