#
# eco
# by Auxilor
# Default config (With Comments) can be found here: https://github.com/Auxilor/eco/blob/master/eco-core/core-plugin/src/main/resources/config.yml
#

data-handler: yaml
display-frame-ttl: 17
health-fixer: false
log-full-extension-errors: false
no-update-checker: false
conflicts:
  whitelist:
  - eco
mysql:
  threads: 2
  database: database
  password: passy
  port: 3306
  host: localhost
  user: username
  connections: 10
mongodb:
  url: ''
use-safer-namespacedkey-creation: false
use-display-frame: true
use-lower-protocollib-priority: false
use-fast-collated-drops: true
perform-data-migration: true
displayed-recipes: true

