#
# EcoEnchants
# by Auxilor
#

anvil:
  cost-exponent: 0.95
  use-rework-penalty: true
  enchant-limit: -1
raytrace-distance: 80
cannot-afford-type:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
enchanting-table:
  cap: 5
  book-multiplier: 0.5
  reduction: 2.2
  enabled: true
  maximum-obtainable-level: 30
cooldown:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
loot:
  book-multiplier: 0.5
  reduction: 7.5
  enabled: true
point-names:
  example_point: Nicely Formatted Point
enchant-gui:
  enchant-area:
    width: 7
    column: 2
    row: 3
    height: 3
  empty-item: gray_stained_glass_pane name:""
  custom-slots: []
  rows: 6
  title: Enchant GUI
  item-column: 5
  item-row: 1
  page-change:
    forwards:
      item: arrow name:"&fNext Page"
      column: 6
      row: 6
    backwards:
      item: arrow name:"&fPrevious Page"
      column: 4
      row: 6
  mask:
    pattern:
    - '111101111'
    - '111111111'
    - '100000001'
    - '100000001'
    - '100000001'
    - '111111111'
    items:
    - black_stained_glass_pane
  info:
    item: player_head name:"&aHow do I use this?" texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjcwNWZkOTRhMGM0MzE5MjdmYjRlNjM5YjBmY2ZiNDk3MTdlNDEyMjg1YTAyYjQzOWUwMTEyZGEyMmIyZTJlYyJ9fX0=
    lore:
    - '&fPlace an item in the slot at the top,'
    - '&fand all the enchantments you can add'
    - '&fto to this item will show up in the'
    - '&farea below!'
    column: 9
    row: 1
cannot-afford:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
villager:
  book-multiplier: 0.14
  reduction: 5
  enabled: true
display:
  above-max-level:
    level-only: true
    format: <gradient:#1D976C:#93F9B9>
    enabled: true
  numerals:
    threshold: 10
    enabled: true
  sort:
    rarity-order:
    - common
    - uncommon
    - rare
    - epic
    - legendary
    - special
    - veryspecial
    length: false
    type: false
    type-order:
    - normal
    - special
    - curse
    rarity: false
  descriptions:
    word-wrap: 32
    format: '&8'
    threshold: 5
    enabled: true
  enabled: true
  require-enchantable: true
  collapse:
    delimiter: ', '
    threshold: 9
    per-line: 2
    enabled: true
lore-conversion:
  aggressive: false
  enabled: false
share-configs: true
potions:
  icon:
    triggered: true
    permanent: true
  ambient:
    triggered: true
    permanent: false
  particles:
    triggered: true
    permanent: false
enchantinfo:
  item:
    lore:
    - ''
    - '&fMax Level: &a%max_level%'
    - '&fRarity: &a%rarity%'
    - '&fApplicable to: &a%targets%'
    - '&fConflicts with: &a%conflicts%'
    column: 5
    row: 2
    show-max-level: true
    line-wrap-format: '&a'
  custom-slots: []
  rows: 3
  mask:
    pattern:
    - '111111111'
    - '111101111'
    - '111111111'
    items:
    - black_stained_glass_pane
use-faster-move-trigger: true

