config_version: 1
debug_messages: false
expire_groups:
  default:
    permission: deathchestpro.expire.default
    teleport_cost: 2000
    chest_block: CHEST
    unlock_after: -1
    time: 3600
allow_break_chests: false
allow_killer_looting: false
drop_items_after_expire: true
lava_spawning: true
lava_protection: true
old_lava_protection: false
void_spawning_chest: false
auto_equip_armor: true
clickable_message: true
spawn_chest_on_highest_block: false
spawn_chest_on_pvp_kill: true
start_timer_at_death: false
store_experience: false
overworld_new_height: true
store_experience_percent: 100.0
max_player_chests: 10
teleport_cooldown: 5
deathchest_fireworks:
  # Should fireworks spawn?
  enabled: false
  # Interval between each firework
  interval: 5
disabled_worlds:
- example_world
disabled_regions:
- example_region
sounds:
  click: UI_BUTTON_CLICK
  gui_open: ENTITY_EXPERIENCE_ORB_PICKUP
hologram:
  # Should hologram be enabled?
  enabled: true
  # Date format. Visit https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html for more help
  death_date_format: dd.MM.yyyy hh:mm
  # Lines displayed on hologram. Accepts placeholders %locked%, %death_date%, %player%, %timeleft%
  lines:
  - '%locked%'
  - '%item_count% Items / %xp% XP'
  - Died %death_date%
  - 'Owner: %player%'
  - '%timeleft% left'
deathchest_inv_title: '&7%player%''s DeathChest'
placeholders_format:
  location: '%x%, %y%, %z%, %world%'
blacklisted_blocks:
- portal
- bed
- sign
