###################################################################################################################
#   __  __       _       _                                    _             _                          _          #
#  |  \/  | __ _(_)_ __ | |_ ___ _ __   __ _ _ __   ___ ___  | |__  _   _  | | _____ _ __  _ __  _   _| |___   __ #
#  | |\/| |/ _` | | '_ \| __/ _ \ '_ \ / _` | '_ \ / __/ _ \ | '_ \| | | | | |/ / _ \ '_ \| '_ \| | | | __\ \ / / #
#  | |  | | (_| | | | | | ||  __/ | | | (_| | | | | (_|  __/ | |_) | |_| | |   <  __/ | | | | | | |_| | |_ \ V /  #
#  |_|  |_|\__,_|_|_| |_|\__\___|_| |_|\__,_|_| |_|\___\___| |_.__/ \__, | |_|\_\___|_| |_|_| |_|\__, |\__| \_/   #
#                                                                  |___/                        |___/             #
###################################################################################################################
# You can report bugs here: https://github.com/kennytv/Maintenance/issues
# If you need any other help/support, you can also join my Discord server: https://discord.gg/vGCUzHq
# The config and language files use MiniMessage, NOT legacy text for input. Use https://webui.adventure.kyori.net/ to edit and preview the formatted text.
# For a full list of formats and fancy examples of MiniMessage, see https://docs.adventure.kyori.net/minimessage/format.html

# Enables maintenance mode.
maintenance-enabled: false

# The message shown in the multiplayer server list motd when maintenance is enabled.
# If you put in multiple entries, one of them will be chosen randomly on every ping.
# If running an endtimer, the time left can be displayed by including '%TIMER%' in a pingmessage (also works in playercount(-hover) message).
pingmessages:
- <dark_gray><bold>>></bold><dark_gray> <gold><bold>BAD OMEN</bold></gold> <white><bold>RPG 1.19.2</bold></white> <dark_gray><bold><<</bold><dark_gray><br><white>Em manutenção, já volta!!!</white>
enable-pingmessages: true
commands-on-maintenance-enable: []
commands-on-maintenance-disable: []
enable-timerspecific-messages: true
timerspecific-pingmessages:
- <red>Currently under maintenance<br><gradient:#fbffc2:#fffff>Come back in:</gradient> <color:#aa55ee>%TIMER%
enable-playercountmessage: true
playercountmessage: <dark_red>Maintenance
playercounthovermessage: <red>Currently under<br><red>maintenance
custom-maintenance-icon: false
send-join-notification: false
kick-online-players: true
language: en
continue-endtimer-after-restart:
  enabled: false
  end: 0
timer-broadcast-for-seconds:
- 1200
- 900
- 600
- 300
- 120
- 60
- 30
- 20
- 10
- 5
- 4
- 3
- 2
- 1
update-checks: true
config-version: 6
