#
# EcoArmor
# by Auxilor
#

discover-recipes: true
raytrace-distance: 80
cannot-afford-type:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
cooldown:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
point-names:
  example_point: Nicely Formatted Point
cannot-afford:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
advanced-lore-only: true
update-item-names: true
potions:
  icon:
    triggered: true
    permanent: true
  ambient:
    triggered: true
    permanent: false
  particles:
    triggered: true
    permanent: false
use-faster-move-trigger: true

