#
# EcoJobs
# by Auxilor
#

level-gui:
  progression-slots:
    next-page:
      material: arrow
      name: '&fNext Page'
      location:
        column: 6
        row: 6
    pattern:
    - 109ab0jkl
    - 2080c0i0m
    - 3070d0h0n
    - 4560efg0o
    - 00000000p
    - 00000000q
    in-progress:
      item: yellow_stained_glass_pane
      lore:
      - '&f'
      - '&fRewards:'
      - '%rewards%'
      - '&f'
      - '&fProgress:'
      - '&8» &e%percentage_progress%%'
      - '&8» &e%current_xp%&8/&7%required_xp% &fXP'
      name: '%job% &fLvl. &a%level%'
    unlocked:
      item: lime_stained_glass_pane
      lore:
      - '&f'
      - '&fRewards:'
      - '%rewards%'
      - '&f'
      - '&aUNLOCKED'
      name: '%job% &fLvl. &a%level%'
    level-as-amount: true
    locked:
      item: red_stained_glass_pane
      lore:
      - '&f'
      - '&fRewards:'
      - '%rewards%'
      name: '%job% &fLvl. &a%level%'
    close:
      material: barrier
      name: '&cClose'
      location:
        column: 5
        row: 6
    prev-page:
      material: arrow
      name: '&fPrevious Page'
      location:
        column: 4
        row: 6
  custom-slots: []
  rows: 6
  close:
    material: barrier
    name: '&cClose'
    location:
      column: 5
      row: 6
  mask:
    pattern:
    - '111111111'
    - '111111111'
    - '111111111'
    - '111111111'
    - '111111111'
    - '111111111'
    materials:
    - black_stained_glass_pane
raytrace-distance: 80
cannot-afford-type:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
cooldown:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
point-names:
  example_point: Nicely Formatted Point
cannot-afford:
  in-actionbar: true
  sound:
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
    enabled: true
level-up:
  message:
    message:
    - '&f'
    - ' &#964B00You levelled up %job%&#964B00 to &eLevel %level%&#964B00!'
    - '&f'
    - ' &#964B00&lREWARDS:'
    - ' %level_up_messages%'
    - '&f'
    enabled: true
  sound:
    id: entity_player_levelup
    pitch: 1.3
    enabled: true
potions:
  icon:
    triggered: true
    permanent: true
  ambient:
    triggered: true
    permanent: false
  particles:
    triggered: true
    permanent: false
gui:
  next-page:
    item: arrow
    name: '&fNext Page'
    location:
      column: 7
      row: 6
  job-info:
    no-active:
      item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19
      lore:
      - ''
      - '&cYou do not currently have a job active'
      - '&fPick one from the options below!'
      - ''
      name: '&cNo Active Job'
    column: 2
    active:
      name: '%job% &fLvl. &a%level%'
      lore:
      - '%description%'
      - '&f'
      - '&fJob Rewards:'
      - '%effects%'
      - ''
      - '&fProgress:'
      - '&8» &e%percentage_progress%%'
      - '&8» &e%current_xp%&8/&7%required_xp% &fXP'
      - ''
      - '&eClick to view Level Progression!'
    row: 2
  deactivate-job:
    item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTRiZDlhNDViOTY4MWNlYTViMjhjNzBmNzVhNjk1NmIxZjU5NGZlYzg0MGI5NjA3Nzk4ZmIxZTcwNzc2NDQzMCJ9fX0=
    name: '&cDeactivate Job'
    location:
      column: 2
      row: 4
  custom-slots: []
  rows: 6
  job-area:
    top-left:
      column: 4
      row: 2
    bottom-right:
      column: 8
      row: 4
  close:
    item: barrier
    name: '&cClose'
    location:
      column: 6
      row: 6
  mask:
    pattern:
    - '111111111'
    - '101000001'
    - '111000001'
    - '101000001'
    - '111111111'
    - '111100011'
    materials:
    - black_stained_glass_pane
  job-icon:
    lore:
    - '%description%'
    - '&f'
    - '&fJob Rewards:'
    - '%effects%'
    - ''
    - '&fProgress:'
    - '&8» &e%percentage_progress%%'
    - '&8» &e%current_xp%&8/&7%required_xp% &fXP'
    name: '%job% &fLvl. &a%level%'
    active-lore:
    - ''
    - '&cThis job is already active!'
    click:
      pitch: 1
      sound: ui_button_click
    not-active-lore:
    - ''
    - '&eClick to activate this job!'
  prev-page:
    item: arrow
    name: '&fPrevious Page'
    location:
      column: 5
      row: 6
use-faster-move-trigger: true

